name: TagBot Triggers
on:
  pull_request:
    types:
      - closed
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  trigger:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Cache artifacts
        uses: julia-actions/cache@d10a6fd8f31b12404a54613ebad242900567f2b9 # v2.1.0
      - run: chmod 400 .ci/Project.toml
      - run: julia --color=yes -e 'import Pkg; Pkg.Registry.add("General")'
        env:
          JULIA_PKG_SERVER: ""
      - run: julia --color=yes -e 'import Pkg; Pkg.Registry.update()'
      - run: chmod +x .ci/instantiate.sh
      - run: .ci/instantiate.sh
      - run: julia --color=yes --project=.ci/ -e 'import Pkg; Pkg.precompile()'
      - run: julia --color=yes --project=.ci/ -e 'using RegistryCI.TagBot; TagBot.main()'
        env:
          GITHUB_TOKEN: ${{ secrets.TAGBOT_TOKEN }}
